### ISSUE TITLE
Look for places with redundant images in the post-execution

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#141]
Generate the notebooks, execute them all with the script, and then look for repetive images.

Some of the static assets could really be reorganized and removed, where executed figures are preferred.

**Comment by arnavs** [comment]
@yolsever If you have some free time, this would be a good cleanup task to tackle. 

Since we're having some trouble with the images displaying in the Jupyter Lab interface, this is probably best done by looking at the website: lectures.quantecon.org/jl 

Essentially, go through each lecture and flag whenever we have an image that's redundant (i.e., we have a plot, and then underneath it we have a static include of a picture of the plot). We can then delete those images and `:figure:` statements. 

Also see #471, which would be a good next step.

**Comment by yolsever** [comment]
Job Search IV: Modeling Career Choice
ex 1 & soln has duplicate images
