### ISSUE TITLE
Maximize pass

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#158]
`Optim.jl` now supports the univariate `maximize` function instead of just `optimize`

We should find all of the places that use `optimize` and convert to `maximize` if that is the math implementation.  Of course, since this si a move from `minimize` to `maximize`, this means swapping the sign of the objective that is passed in as well *not* swapping the sign of the output 

Also, look for http://quantecon.github.io/QuantEcon.jl/latest/api/QuantEcon.html#QuantEcon.golden_method-Tuple{Function,Real,Real} and swap that out as well.

**Comment by arnavs** [comment]
@XiaojunGuan I think this is a good one to start on. Basically, we have a lot of maximization problems that are coerced into the structure of a minimization problem, because that's what `Optim.jl` used to support. 

https://github.com/JuliaNLSolvers/Optim.jl/issues/554 is some background on the optimizer, but to see the exact usage you can look at the tests in the Optim package.

**Comment by Nosferican** [comment]
ifp.rst needs a pass.

**Comment by Nosferican** [comment]
Any update on that?

**Comment by arnavs** [comment]
Done at e4697c6; thanks for the reminder @Nosferican.
