### ISSUE TITLE
Possible setup instructions for a docker based quantecon

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#174]
From https://github.com/ubcecon/computing_and_datascience/tree/master/docker#how-to-get-docker-running-on-your-laptop

- [x] image with the `activate_github` and the `] add ...` precompiled, etc. 
- [x]  Pointer for instructions to download docker
- [x] Then how to run docker in a local folder, and at least read notebooks, something like
```
docker run -p 8888:8888 -v "$PWD":/home/jovyan/work quantecon/jupyter-image
```
Try on windows, osx, and linx
- [x] How to start the docker again.
- [x] How to access the notebooks there, what to copy for the URL string, etc. 
- [x] Test that GRL works

**Comment by arnavs** [comment]
OK @jlperla I think this is complete. See [the UBCEcon repo](https://github.com/ubcecon/computing_and_datascience/tree/master/docker). 

Each image comes with our usual set of packages (i.e., `Expectations Parameters Plots InstantiateFromURL QuantEcon IJulia DifferentialEquations Interpolations...`). 

The headless image is about 3 GBs, with roughly 1.7 coming from our installed/precompiled packages, 0.5 coming from the base Julia image, and 0.5 coming from the Linux dependencies necessary for plots. The additional 0.3 is Jupinx/Miniconda. 

The interactive image is about 6 GBs, with about 0.5 coming from our packages (smaller most likely because of pre-existing resources), 0.5 coming from Conda dependencies for R, 0.3 from Julia itself, and the rest from the base image. This is bigger than the one Jasmine was experimenting with, because we based it off of the full `jupyter/datascience-notebook` instead of picking and choosing.

**Comment by jlperla** [comment]
Are we using the InstantiateFromURL here to install/precompile all of QELP?  Remember that we want this to work with them precompiled out of the box to be compatible with the lecture notes.

But before we do that... lets try to get the image size down.  I think we should do the following:
- [ ] Make a version of the QELP v0.4 where we remove `DifferentialEquations, Dierckx, Interact, DiffEqCallbacks` 
 - Add in `LazyArrays, FillArrays` as well, but these are dependencies of banded, so it won't add anything
 - Do a general `] up` afterwards.
 - We should check that the manifest.toml is *significantly* shorter, and we can test with the `ECON_628` notebooks to make sure there isn't any issue after we move to `v0.4`
 - If there are a few lecture notes that use `Dierckx`, people can add it as required.
- [ ] Remove the `DifferentialEquations DiffEqBase` from the headless and interactive ones as well
- [ ] Add in the `using InstantiateFromURL; activate_github("QuantEcon/QELP", "v0.4")` or whatever into both of the images
- [ ] We should then have separate `headless-diffeq` and `interactive-diffeq` images which use these other two as bases, but simply do a `add DifferentialEquations DiffEqBase DiffEqCallbacks Interact Sundials; precompile` to them.  This gives an option for a precompiled, massive image with all the diffeq stuff in it.
  - I am not sure if you can do this prior to putting the first two as official docker images on the QuantEcon docker build (because we use it as a base image).  We can get the login info from Matt, although it is possible jasmine already has it.

**Comment by arnavs** [comment]
OK, sounds good. We can also remove R stuff and try and delete unnecessary cache files.

**Comment by jlperla** [comment]
I am more worried about the compilation overhead of the DifferentialEquations  for the interactive one.  If there is any change to their packages, at that point it can make a couple-dozen compilations necessary.

**Comment by arnavs** [comment]
All sounds good to me. And agree that we shouldn’t have everything be a minor release.

**Comment by arnavs** [comment]
OK, done: 

1. Results of moving to v0.3.1: `11 insertions(+), 352 deletions(-)`
2. New image sizes (sans diff eq/etc., post QELP v0.3.1) are 

I'll wait for the Docker credentials from @mmcky and upload these. Maybe the naming scheme could be something like `QuantEcon/julia-1.0.1:headless`, `QuantEcon/julia-1.0.1:headless-plus`, `QuantEcon/julia-1.0.1:main`, `QuantEcon/julia-1.0.1:main-plus`? That way, we can load the massive ones with anything foreseeable (`Optim`, `NLsolve`, etc).

**Comment by arnavs** [comment]
Closing this because we now have the https://github.com/QuantEcon/docker/pulls/2
