### ISSUE TITLE
Separating the `seed` for testing vs. non-testing code

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#232]
The current code has a lot of `Random.seed!(42)` in front of MANY cells in the notebooks.

I imagine that the reason for this is that the tests where randomness is provided are otherwise impossible to run out of sequence?  Having a single one at the top is fine, but it looks ugly to have so many.

If there is no way around resetting things before every test section, then I think we should move those seeds to test-blocks (maybe on their own) right before their current locations.  Then things will be deterministic for testing purposes, but the code won't be cluttered for readers.

**Comment by arnavs** [comment]
@XiaojunGuan, if I recall, you're out of tasks to complete on this project? If you could take a stab at this, that would be great (this is basically test manipulation). 

The idea is that we want to make sure that tests are runnable out of sequence (that is, in any order that compiles). This is tricky because the tests depend sometimes on random objects. What we've done is to sprinkle `Random.seed!(42)`s everywhere at the start of cells (which resets the seed before running that particular cell). But, as Jesse points out, this is an ugly and distracting solution. 

I don't think we'll have time before the release on c. Nov. 5 to refactor the whole tests. So, what we should do is the solution above (move the random seeds to test blocks, which contain only the one command) right before their current locations). That way, as @jlperla pointed out, we can keep the current tests/values for development, but get rid of the noise for end users.

**Comment by XiaojunGuan** [comment]
Okay, I will try to get it done by tomorrow.

**Comment by arnavs** [comment]
Thanks so much.

**Comment by XiaojunGuan** [comment]
@arnavs Finished. Please see PR #238.

**Comment by arnavs** [comment]
Closed by #238
