### ISSUE TITLE
Equation's label sometimes doesn't display its number in Julia's jupyter notebook.

### ISSUE THREAD

**Issue by PooyaFa** [QuantEcon/lecture-source-jl#250]
I solved this problem in a very bad way: I changed some lines in sphinxcontrib-jupyter/sphinxcontrib/jupyter/writers/translate_all.py

However, it needs a very better solution.

**Comment by jlperla** [comment]
Thanks Pooya. Let's hold off from making changes in the underlying code sphinx which generates them for now. But documenting it helps for submitting a bug to the those people.

In all of these cases, when you are saying that it "sometimes " happens, can you always give a pointer to the exact file and equation as an example? If it happens in many places, just start with a specific example so that the people changing Sphinx can start with something specific.

Finally, taking a small screenshot of the place that looks weird is helpful for the issue

**Comment by arnavs** [comment]
Hey @PooyaFa, any update on this? Like Jesse said above, if you can submit a minimal example and bug to the Jupinx repo, that would be great.

**Comment by PooyaFa** [comment]
Here is an example:

https://github.com/QuantEcon/sphinxcontrib-jupyter/issues/136#issuecomment-436052896

**Comment by arnavs** [comment]
Thanks so much @PooyaFa, closing because we have a duplicate issue now.
