### ISSUE TITLE
Test on docker setup

### ISSUE THREAD

**Issue by XiaojunGuan** [QuantEcon/lecture-source-jl#305]
One problem with the docker setup instruction in getting_started is that the URL `http://127.0.0.1:8888/lab` is not working. It says that the requested page does not exist.

**Comment by arnavs** [comment]
Hey @XiaojunGuan could you share a screenshot of the terminal output and the web browser?

**Comment by XiaojunGuan** [comment]
<img width="1045" alt="terminal" src="https://user-images.githubusercontent.com/35314124/48454000-74fbaa80-e76a-11e8-824e-11d17caf4c51.png">

<img width="1438" alt="url" src="https://user-images.githubusercontent.com/35314124/48454010-85ac2080-e76a-11e8-87da-e75f20ee7877.png">

**Comment by arnavs** [comment]
Thanks. I wonder if this is because of the space in the directory name `QuantEcon Docker`. 

Will troubleshoot with @XiaojunGuan and then post results here.

**Comment by arnavs** [comment]
The issue was that we had an existing notebook server running on port `8888` but the failure was silent. We should add in a note to make sure that `jupyter notebook list` is clear, and tell people to`jupyter notebook stop` if it isn't. 

Closing this and making a new issue. Will also include the check on the installation. Thanks @XiaojunGuan
