### ISSUE TITLE
I + zeros(...

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#318]
We adopt this pattern when we need to (for ex.) concatenate an identity matrix with a concrete one, or pass objects to functions in `QuantEcon.jl` that don't accept the generic `UniformScaling`.

Should eventually either patch the package or something. See #314 #316 etc.

**Comment by jlperla** [comment]
I am not sure if this is worth establishing as a pattern, since a `Diagonal` is certainly better when `I` doesn't work.  If the purpose of this issue is to rewrite certain code in certain lectures to support `I`, then maybe change the title to make that more clear?

**Comment by jlperla** [comment]
Yeah, concatenation with abstract matrices is usually pretty smart.

@arnavs I guess I just don't understand what the problem in the old lecture was.  My feeling is that we should always stick with the lazy and/or specialized matrices as much as possible.  If you ran into a few cases where it doesn't work, then we can find a temporary workaround... but I don't think the pattern proposed is something to be considered as anything other than a temporary "hack" until the real solution is found.

I just don't understand what this issue is about and would prefer to remove it unless there is something specific to do.

**Comment by arnavs** [comment]
There were two cases. One was the concatenation, which works (I didn’t know it does). And the other is the passing objects to “dumb” functions in QuantEcon.jl. 

Havent played with ‘Diagonal’, but I’ll give it a shot and see if it works. Can re-open if it doesn’t.
