### ISSUE TITLE
Sanity Check on amss

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#324]
We just merged #159. This came with a lot of code changes and a few math ones (for example, moving to linear interpolation and relaxing the error tolerance a bit). 

We need to do a smoke-test of the output vs. the lectures.quantecon.org/jl/amss.html It looks like @Nosferican shifted the plot scale a bit, so perhaps he could weigh in here as to some of the more visible differences in the y-axis. 

As mentioned, we're really nearing the finish line, so working on this sooner rather than later would be appreciated. Ping me on slack if anything is unclear.

**Comment by ajozefiak** [comment]
I believe that for the second set of plots in the examples, the plots with blue triangles should be labeled incomplete markets as opposed to complete markets. 

In terms of the first set of plots, I've noticed that in the merged amss lecture the peace-time incomplete market time series generally follows the war-time incomplete market time series (with the exception of the government spending plot) as opposed to following the complete markets time series like in the example in lectures.quantecon.org/jl/amss.html.  

In terms of numerical-errors, I tried the original python lecture, whose output appears to correspond to the lecture displayed at lectures.quantecon.org/jl/amss.html, and the merged amss lecture has about a order of magnitude more numerical error when solving the Bellman equation. Although this is due to the relaxed error tolerance, in one test I had one of the iterations for the first code snippet in the examples section terminate in the same order of magnitude of error as the python lecture and this caused this first of plots to have the peace-time incomplete market time series move closer to the complete markets time series. 

I am not necessarily sure if the relaxed error is the cause of this discrepancy and if the discernment between peace-time vs war-time incomplete markets is as critical as in lectures.quantecon.org/jl/amss.html.

**Comment by arnavs** [comment]
Thanks for working on this @ajozefiak; I'm actually pinning down the source of the error rn and was about to pass this off to you. Will incorporate this useful feedback and post here.

**Comment by arnavs** [comment]
OK @ajozefiak you can look at the latest version on master

**Comment by arnavs** [comment]
Also, if you could include `Random.seed!`s in test blocks where appropriate and add unit tests for the invariants (mainly the last plot, the other two consistently match exactly), would be great.

**Comment by arnavs** [comment]
Done with your last PR
