### ISSUE TITLE
some issues about "Solvers, Optimizers, and Automatic Differentiation" lecture

### ISSUE THREAD

**Issue by PooyaFa** [QuantEcon/lecture-source-jl#382]
1. Which notation is correct for partial derivatives: \frac{\partial y}{\partial x_1}  or \frac{d y}{d x_1}
![1](https://user-images.githubusercontent.com/44382270/48753890-92d27f00-ec44-11e8-9723-1916fdd6346c.PNG)

2.this part of a code is not clear and demonstrating well enough how the functions are working. I am suggesting these changes in  the screenshot (using ``@show``) line 254 in rst file: 
![2](https://user-images.githubusercontent.com/44382270/48753911-abdb3000-ec44-11e8-82b3-134bd513c035.PNG)
![2i](https://user-images.githubusercontent.com/44382270/48753912-abdb3000-ec44-11e8-91f3-70ba00746065.PNG)

3. the same issue as above for the next julia code:
![3](https://user-images.githubusercontent.com/44382270/48753926-b5fd2e80-ec44-11e8-8778-88e736d28136.PNG)
![3i](https://user-images.githubusercontent.com/44382270/48753927-b5fd2e80-ec44-11e8-95f5-97d9dceb7fd9.PNG)

4. I don't understand what inconsistencies it referrers to: rst line 272
![4](https://user-images.githubusercontent.com/44382270/48753936-c0b7c380-ec44-11e8-9bd2-3e2ec1f91f8b.PNG)

5. Did you mean ForwardDiff.jl or  finite-differences or  DiffEqDiffTools.jl ? I didn't understand this part: rst line 299
![5](https://user-images.githubusercontent.com/44382270/48753953-cd3c1c00-ec44-11e8-91ec-b88fe86784ff.PNG)

6. There is no file name generic_tips_tricks or tips and trick, I mentioned to this problem in previous lectures: rst line 312
![6](https://user-images.githubusercontent.com/44382270/48754067-391e8480-ec45-11e8-98ee-8156c2d152b3.PNG)

7. What is ``Ipopt`` ? it isn't mentioned in the lecture. rst line 357 
![7](https://user-images.githubusercontent.com/44382270/48754136-7125c780-ec45-11e8-9b9b-de6c4d1502e2.PNG)

8.  I think it is good to show the solution. It is not mentioned here. rst line 357
![8](https://user-images.githubusercontent.com/44382270/48754143-76831200-ec45-11e8-9a6c-6ab98f329cad.PNG)

9. Again I suggest that we use `@show` for these types of codes: rst line 535
![9](https://user-images.githubusercontent.com/44382270/48754147-7b47c600-ec45-11e8-96ed-aecfbee66da4.PNG)

**Comment by arnavs** [comment]
Hey @PooyaFa, responses:

1. I think both are correct, but we should be consistent. I think the `\partial` symbol is a good visual reminder that the function has several variables, so I moved over to it.

2. I don't think `@show` is the best pattern here, but I added in some sentences 

3. Resolved by the above.

4. The inconsistency is that with one we called `result.minimizer` and `result.minimum`, and with the other we called `maximizer(result)` and `maximum(result)`. Edited the words.

5. Since we don't use the Julia package directly, I edited the link to point to the Wikipedia for finite differences.

6. Note that you don't need to link to a file, but you can also refer to parts of files. Here though, I don't think this section exists, so I just pointed it at the generic programming lecture.

7. OK, I put in a line about what Ipopt is 

8. Done 

9. This is OK, since we print the result.
