### ISSUE TITLE
Remove all static files not in use

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#471]
Basically, after this is done in https://github.com/QuantEcon/lecture-source-jl/tree/master/rst_files/_static we should only have files actually used in the generation of the lecture notes.

For the static images and headers, keep in mind that these may now be using the url prefix, so we should check carefully whether it is actually used in the testing of local notebooks

**Comment by jlperla** [comment]
Might want to do #270 first so that you can cleanup all of the header inclusions in https://github.com/QuantEcon/lecture-source-jl/tree/master/rst_files/_static/includes   (I am worried about us bumping a version in one of them and forgetting to do it in another) 

I would also prefer to flatten the structure used for literal includes as well, now that they are being used much less frequently.  That is, things like https://github.com/QuantEcon/lecture-source-jl/tree/master/rst_files/_static/code could be moved to the higher level.

I am also not so sure why those would be in a different location than the other https://github.com/QuantEcon/lecture-source-jl/tree/master/rst_files/_static/includes

**Comment by arnavs** [comment]
@XiaojunGuan Since you've got a window of time, I think this would be useful to knock off. Basically, for every static file in `~/rst_files/_static` or whatever, if you do a control+f across the whole repo for the filename and nothing significant comes up, we can delete the file. 

And the thing about flattening is to get rid of the sub directories of the `_static` directory (and change the references to those files accordingly). 

Let me know if I've left anything unclear.
