### ISSUE TITLE
Run regression test of a single notebook within the docker environment

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#489]
After #488 we can try to run a regression test of a single notebook after running the jupyter.

Talk to @mmcky about how he is currently running a given notebook, which we could figure out how to call or add to the repo.

(Alternatively, it may be possible to use https://github.com/stevengj/NBInclude.jl to include the code and run it, but I think the existing alternatives may be better because I think the `skip-test` block is useful.).

**Comment by arnavs** [comment]
@ajozefiak will be working on this. 

Just to rehash our covnersation, the game plan is to first get figure out how to programmatically test a notebook (maybe borrowing from the `./run-notebook.sh` script I showed you) in Docker, at which point we could plug this into Travis. 

The docker framework we're using is at https://github.com/arnavs/jupinx-docker. Still WIP, but it works for this (i.e., building the lectures). You'd have to mount the `lecture-source-jl` repo instead of the `mmcky/quantecon.build.lectures`, and instead of `make foobar` you'd be running `make jupyter-tests`. 

Ping me or post here if anything's unclear.
