### ISSUE TITLE
Git LFS + Jupyter

### ISSUE THREAD

**Issue by arnavs** [QuantEcon/lecture-source-jl#514]
See if this is a better way to version the notebook repositories. 

https://github.com/QuantEcon/lecture-source-jl/issues/509#issuecomment-451320826

**Comment by jlperla** [comment]
To upload and update via LFS requires the commandline. Create a simple repo and check if it works well.

Cloning should be seamless, hopefully, where the user is ignorant of the distinction? 

The things to check are that cloning works on:
- [ ] github desktop... By default or whether something additional is required for installation
- [ ] syzygy nbgitpuller.
- [ ] a git installation other than github desktop. Does it require anythinf to install to clone? (ie not pushing changes)

If those work, we can test out other scenarios

**Comment by jlperla** [comment]
Note that with https://github.com/isaacs/github/issues/712 there is no ability to download a zip with the files.  I don't think this is a major issue, but something to consider as a small tradeoff.

**Comment by jlperla** [comment]
@arnavs  Can you
- [ ] Collect the right link for setup instructions here for people to try if they are not using GitHub Desktop
  * My preference would be that there is a link to the best installation documentation (which may just be the main LFS link)
  * For Ubuntu/decian, I think we should consider putting in the actual code to run.  Instead of the step being to download, we should use `curl` and then call the shellscript in the same line if possible so it is idiotproof.
- [ ]  And just to check that we tried the github desktop on osx directly from the repository link, where lfs was not already installed?

On Windows at least, we should say:
> On opening the repository, if you have not previously used Git LFS, choose to "Initialize Git LFS" at the prompt

I suspect it would be the same on OSX and Linux.

**Comment by arnavs** [comment]
Hey @jlperla, here it is: 

1. We get the same popup on OSX, yeah. 

2. For install, I think the [Wiki page](https://github.com/git-lfs/git-lfs/wiki/Installation) we were looking at is best for Linux users (i.e., it'll give you the shell scripts). For OSX/Windows users without GitHub Desktop, the [main website](https://git-lfs.github.com) with the binaries is probably the best approach.

**Comment by arnavs** [comment]
Hey @yolsever, can you give the Linux instructions above a go on your WSL setup? That is- 

1. `curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash`
2. `sudo apt-get install git-lfs`
3. `git lfs install`

AFAIK, the WSL setup uses Ubuntu 18 (?), so you can ignore the bit about adding the new repository for Ubuntu 12. (But, if I'm wrong, then you need to do that first).

**Comment by arnavs** [comment]
Also, beyond the setup, just make sure that you can run `git clone https://github.com/arnavs/git-lfs-test` and open it up in Jupyter and see a bunch of notebooks (as opposed to a bunch of short pointer files to notebooks).

**Comment by arnavs** [comment]
@yolsever is finding a connection refused from `curl`. 

I think this is an open WSL issue: https://github.com/Microsoft/WSL/issues/2690

Will make a note of this in the instructions, thanks Kaan for testing

**Comment by jlperla** [comment]
Sounds good. WSL isn't a big target, just convenient for testing. So if it doesn't work, then so be it

**Comment by jlperla** [comment]
After #522 I think you should close this.
