### ISSUE TITLE
Condider changing the `dev` example to use local directory instead of `.julia/dev`

### ISSUE THREAD

**Issue by jlperla** [QuantEcon/lecture-source-jl#662]
I think we should try to see if training people to put their own packages outside of `.julia/dev`... especially if we tell them to occasionally nuke the `.julia` directory.

Where this would mainly bind is in: https://lectures.quantecon.org/jl/more_julia/testing.html

We should tell people how to do the `develop --local ExamplePackage` or whatnot as well... And tell them that without the `--local` it goes to `~/.julia/dev`

**Comment by arnavs** [comment]
@jlperla This one is a bit complicated, since `--local` puts it in a `dev` folder under the current Julia project. So if I navigate to a folder, fire up a REPL, and `] dev --local SomePackage`, it won't do anything without `] activate .`

Probably a better workflow is to `git clone` a package, cd to that (or open it in GitHub desktop/Atom or something), and run `] dev .`

Let me know what your thoughts are on this issue.

**Comment by jlperla** [comment]
Closing then.  The way we have it now is cleaner than that.
