### ISSUE TITLE
Plot in Lecture Job Search I: The McCall Search Model

### ISSUE THREAD

**Issue by TAGElena** [QuantEcon/lecture-source-jl#785]
I believe there could be an error on the first graph of the Lecture; the current plot might not be showing the true distribution of wages that the model is using.

When we later compute the expectation of the distribution we obtain a value of 43.33, yet the current (symmetric) plot would indicate the expected wage should be around 35. I believe the following alternative plot represents the true wage distribution the model is actually using.

```
using InstantiateFromURL
github_project("QuantEcon/quantecon-notebooks-julia", version = "0.4.0")
using Distributions, Expectations, StatsPlots
n = 50
dist = BetaBinomial(n, 200, 100) # probability distribution
@show support(dist)
w = range(10.0, 60.0, length = n+1) # linearly space wages
plt = plot(w,pdf.(dist, support(dist)), xlabel = "wages", ylabel = "probabilities", legend = false)
```

There might be something regarding the distribution that I do not understand, I am only concerned about the correspondence between the expectation I would expect from the graph and that which I later compute with the expectation operator.

**Comment by jlperla** [comment]
@TAGElena Thanks so much.  We will analyze.  @arnavs  Can you investigate?

**Comment by arnavs** [comment]
Thanks @TAGElena for the good catch. We definitely need to make this clearer. 

The difference is because the support of the wage distribution is `[10, 60]`, but the support object spit back by Julia (which is what gets plotted, etc.) is a vector of indices. That is:  

```
julia> support(dist)
0:50
```

I will update the plotting code to what you describe here. And that should make the plot match reality.
